### ISSUE TITLE
[question] Can a session be active only on a single device (IP address) simultaneously?

### ISSUE THREAD

**Issue by ip** [nikat/mtproto2json#4]
Hi there again. Thanks for your program, it's really indispensable for the job I'm doing at the moment.

@milch @lattenwald
I need a little advice. I used the same session ID and auth key in production and on my local dev server and noticed that the production stopped working with these messages:

```
Timeout, no rpc_response, I am deleting this: {'_cons': 'account.updateStatus', 'offline': {'_cons': 'boolFalse'}}
Timeout, no rpc_response, I am deleting this: {'_cons': 'account.updateStatus', 'offline': {'_cons': 'boolFalse'}}
...
```

Seems like Telegram just started to ignore requests from the production server once I started to use this auth on the development one. Is this correct? If I generate a different token for development and use the separate tokens, should it work?

I just want to make sure I figured things out because unlike Bot API, the client API is somewhat more unexpected.

**Comment by lattenwald** [comment]
There is something about it somewhere in documentation, but as I am too lazy to find it I'll just tell you what I remember.

One auth token can be used only in one software instance; latest connected instance with non-unique auth token gets updates.

Also IIRC only 5 connected clients are allowed, with different tokens.

**Comment by ip** [comment]
Cool, thanks for the info.

**Comment by ip** [comment]
@lattenwald Did you try to run separate instances with different tokens? I just tried and even that doesn't work for some reason - the connection with second token returns this when I'm trying to get dialogs:

```
{"message":{"_cons":"messages.getDialogs","offset_date":0,"offset_id":0,"offset_peer":{"_cons":"inputPeerEmpty"},"limit":0}}
{"id": 0, "message": {"_cons": "bad_msg_notification", "bad_msg_id": 6532118659958832740, "bad_msg_seqno": 3, "error_code": 17}}
```

Although on auth mtproto2json returns "ok".

**Comment by lattenwald** [comment]
@ip yes, I did run two instances for one account with different tokens, one locally for developing and another one on server, production.

**Comment by ip** [comment]
Yeah, I have the same case. Maybe it's because the production server is in a different country.
