### ISSUE TITLE
req_msg_id not found

### ISSUE THREAD

**Issue by ip** [nikat/mtproto2json#6]
This error eventually appears when I stop my production server and launch the development one on my laptop. Have no idea what's the reason, but it usually disappears by itself after some time (i.e. 30 minutes).
Seems that it disappears after restarting my server like 8 times.

**Comment by nikat** [comment]
Hello. Sorry for a late answer.

This message means your client received a response with request id of a request it did not send. 

A telegram session remembers all requests. If you start streamjson.py, then make a request, then quickly restart your client, the new instance will receive a response to a request it did not send. 
This is usually harmless and mtproto2json just drops it. 

If you don't reconnect your client or restart streamjson.py while sending requests, this will not appear. 

Try to make an app that does not drop the connection to streamjson.py and does not restart streamjson.py and 'req_msg_id not found' errors will go away.
